ImageGallery/ImageGallery/Controllers/GalleryController.cs
using ImageGallery.Models.EntityFramework;
using ImageGallery.Models.ImageContext;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImageGallery.Controllers
{
    public class GalleryController : Controller
    {
        ImageDbContext db = new ImageDbContext();
        
        [AllowAnonymous]
        public ActionResult Index()
        {
            var coverImage = db.Galleries.ToList();
            return View(coverImage);
        }
        
        public ActionResult CoverUpload()
        {
            ViewData["error"] = "";
            return View();
        }

        [HttpPost]
        public ActionResult CoverUpload(Gallery CoverPicture, HttpPostedFileBase CoverPath)
        {
            try
            {
                Gallery coverImage = new Gallery();
                coverImage.CoverName = CoverPicture.CoverName;
                coverImage.CoverPath = CoverPath.FileName.ToString();

                var path = Server.MapPath("~/Content/CoverImages");
                CoverPath.SaveAs(Path.Combine(path, CoverPath.FileName.ToString()));
                db.Galleries.Add(coverImage);
                db.SaveChanges();
            }
            catch (Exception ex)
            {

                ViewData["error"] = "Error for Upload";
                return View();
            }
            return RedirectToAction("Index");

        }
        public ActionResult Delete(int id)
        {
            var gallery = db.Galleries.Find(id);
            if (gallery==null)
            {
                return HttpNotFound();
            }
            db.Galleries.Remove(gallery);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ImageGallery/ImageGallery/Controllers/ImageController.cs
using ImageGallery.Models.EntityFramework;
using ImageGallery.Models.ImageContext;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImageGallery.Controllers
{
    public class ImageController : Controller
    {
        ImageDbContext db = new ImageDbContext();
        // GET: Image
        [AllowAnonymous]
        public ActionResult Index()
        {
            var images = db.GaleryImages.ToList();
            return View(images);
        }
        public ActionResult Upload()
        {
            ViewData["error"] = "";
            return View();
        }
        [HttpPost]
        public ActionResult Upload(GalleryImage img,HttpPostedFileBase ImagePath)
        {
            try
            {
                GalleryImage image = new GalleryImage();
                image.ImageName = img.ImageName;
                image.ImagePath = ImagePath.FileName.ToString();

                var path = Server.MapPath("~/Content/Images");
                ImagePath.SaveAs(Path.Combine(path, ImagePath.FileName.ToString()));
                db.GaleryImages.Add(image);
                db.SaveChanges();
            }
            catch (Exception ex)
            {

                ViewData["error"] = "Error for Upload";
                return View();
            }
            return RedirectToAction("Index");
            
        }
        public ActionResult Delete(int id)
        {
            var image = db.GaleryImages.Find(id);
            if (image==null)
            {
                return HttpNotFound();
            }
            db.GaleryImages.Remove(image);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ImageGallery/ImageGallery/Views/Image/Index.cshtml
@model List<ImageGallery.Models.EntityFramework.GalleryImage>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>My Images</h2>
@Html.ActionLink("Upload a Photo", "Upload", new { @class = "btn btn-primary" })
<br />
@Html.ActionLink("Back to Gallery List","Index","Gallery")
<br />
<hr />

<h1 class="font-weight-light text-center text-lg-left mt-4 mb-0"> My Images</h1>


<div id="gallery">
    @foreach (var item in Model)
    {
        <div class="item-container">
            <div class="gallery-item">
                <a href="~/Content/Images/@item.ImagePath" target="_blank">
                    <img src="~/Content/Images/@item.ImagePath" alt="">

                </a>
                <div class="description">
                    @item.ImageName
                </div>
                @Html.ActionLink("Delete", "Delete", "Image", new { id = item.Id }, new { @class = "btn btn=danger", onclick = "return confirm('Are you sure to delete this Image?')" })
            </div>
        </div>
       
    }


</div>

ImageGallery/ImageGallery/Views/Image/Upload.cshtml
@model ImageGallery.Models.EntityFramework.GalleryImage

@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Upload</h2>

@using (Html.BeginForm("Upload","Image",FormMethod.Post,new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GalleryImage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImagePath" class="form-control" />
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>